// Code generated by go-swagger; DO NOT EDIT.

// Copyright Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package manager

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/prometheus/alertmanager/api/v2/models"
)

// NewFlushconfigParams creates a new FlushconfigParams object
// with the default values initialized.
func NewFlushconfigParams() *FlushconfigParams {
	var ()
	return &FlushconfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFlushconfigParamsWithTimeout creates a new FlushconfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFlushconfigParamsWithTimeout(timeout time.Duration) *FlushconfigParams {
	var ()
	return &FlushconfigParams{

		timeout: timeout,
	}
}

// NewFlushconfigParamsWithContext creates a new FlushconfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewFlushconfigParamsWithContext(ctx context.Context) *FlushconfigParams {
	var ()
	return &FlushconfigParams{

		Context: ctx,
	}
}

// NewFlushconfigParamsWithHTTPClient creates a new FlushconfigParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFlushconfigParamsWithHTTPClient(client *http.Client) *FlushconfigParams {
	var ()
	return &FlushconfigParams{
		HTTPClient: client,
	}
}

/*FlushconfigParams contains all the parameters to send to the API endpoint
for the flushconfig operation typically these are written to a http.Request
*/
type FlushconfigParams struct {

	/*Config
	  The config to create

	*/
	Config *models.PostableConfig

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the flushconfig params
func (o *FlushconfigParams) WithTimeout(timeout time.Duration) *FlushconfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the flushconfig params
func (o *FlushconfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the flushconfig params
func (o *FlushconfigParams) WithContext(ctx context.Context) *FlushconfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the flushconfig params
func (o *FlushconfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the flushconfig params
func (o *FlushconfigParams) WithHTTPClient(client *http.Client) *FlushconfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the flushconfig params
func (o *FlushconfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfig adds the config to the flushconfig params
func (o *FlushconfigParams) WithConfig(config *models.PostableConfig) *FlushconfigParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the flushconfig params
func (o *FlushconfigParams) SetConfig(config *models.PostableConfig) {
	o.Config = config
}

// WriteToRequest writes these params to a swagger request
func (o *FlushconfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
